### ISSUE TITLE
Not worked well with image clicked by camera

### ISSUE THREAD

**Issue by Sushobhitbuiltbyblank** [aatish-rajkarnikar/ImageCropper#4]
I am using your code to crop image. your example is working well with demo image but is not work well with the image captured by camera. 
When I tried to crop the image, the image cropped with different coordinates, and the image also rotate. 
Can you please help me out.?

**Comment by aatish-rajkarnikar** [comment]
you need to fix the orientation of the image taken from the camera before performing cropping. you can use the following link to fix the orientation.

https://github.com/cosnovae/fixUIImageOrientation/blob/master/fixImageOrientation.swift

**Comment by Sushobhitbuiltbyblank** [comment]
Thanks for reply..
I use the fixImageOrientation method now. but now clicked image got stretched. I have share the images before and after the implement the method.
![img_0451](https://user-images.githubusercontent.com/13959992/27069931-7bc48e64-5034-11e7-8c31-a32e8594d7f2.PNG)
![img_0452](https://user-images.githubusercontent.com/13959992/27069929-7bc22804-5034-11e7-9383-116a68302d70.PNG)
![img_0453](https://user-images.githubusercontent.com/13959992/27069932-7bc7f8ce-5034-11e7-80a2-96ebca064470.PNG)
![img_0454](https://user-images.githubusercontent.com/13959992/27069930-7bc3a67a-5034-11e7-9027-33391b396061.PNG)

**Comment by aatish-rajkarnikar** [comment]
do you have the **Content Mode** of the **image view** set to **Aspect Fit**

**Comment by Sushobhitbuiltbyblank** [comment]
yes. the content mode of imageview is aspect fit in all case.

**Comment by Sushobhitbuiltbyblank** [comment]
extension UIImage {
func ic_imageInRect(_ rect: CGRect) -> UIImage? {
            
            UIGraphicsBeginImageContext(rect.size)
            
            // Create the bitmap context
            
            guard let context = UIGraphicsGetCurrentContext() else {
                return nil
            }
            
            // Sets the clipping path to the intersection of the current clipping path with the area defined by the specified rectangle.
            
            context.clip(to: CGRect(origin: .zero, size: rect.size))
            
            self.draw(in: CGRect(origin: CGPoint(x: -rect.origin.x, y: -rect.origin.y), size: self.size))
            
            // Returns an image based on the contents of the current bitmap-based graphics context.
            
            let contextImage = UIGraphicsGetImageFromCurrentImageContext()
            
            UIGraphicsEndImageContext()
            
            return contextImage
        }
}
I have implemented this method instead of cropping(to:) of cgimage class now this work fine. 
thanks you

**Comment by aatish-rajkarnikar** [comment]
if your issue has been resolved, you can close it.

**Comment by josepfm** [comment]
@Sushobhitbuiltbyblank in addition to that method (ic_imageInRect), you have previously used fixImageOrientation?

**Comment by josepfm** [comment]
When I run it on a real device, it cuts out a piece of image that doesn't match the one I selected.

**Comment by Sushobhitbuiltbyblank** [comment]
@jose46moreno  yes I used fixImageOrientation also with method (ic_imageInRect)

**Comment by josepfm** [comment]
Can you share the project?

I can't get it to work.

Thanks!
